config/routes.rb
MediaServer::Application.routes.draw do
  get "music/home"

  root 'music#home'

	get 'tracks/gather' => 'tracks#gather'
	get 'tracks/stream/:id' => 'tracks#stream', :as => :stream
  	resources :tracks, :only => [:show, :edit, :update, :index]

	get 'artists/data/:mode' => 'artists#data', :as => :artists_data
	resources :albums, :artists

end

app/models/track.rb
class Track < ActiveRecord::Base
	belongs_to :album
	belongs_to :root
	belongs_to :artist
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
	def stream
		@track = Track.find(params[:id])
		send_file @track.location, type: "audio/mpeg"
	end	
	def show
		@track = Track.find(params[:id])
	end
	
	def index
		@tracks = Track.all.order(:title)
	end
	
	def edit
		@track = Track.find(params[:id])
	end
	
	def update
		@track = Track.find(params[:id])
		
		if @track.update(track_params)
			redirect_to @track
		else
			render 'edit'
		end
	end
	
	private

	def track_params
		params.require(:track).permit(:title, :album_id, :track_no, :artist_id)
	end
end

app/helpers/tracks_helper.rb
module TracksHelper
	def self.musicplayer_script(tracks)
		html = []
		html.push('<script>')
		html.push('var player = new MusicPlayer();')
		tracks.each {|track|
			html.push('player.addToPlaylist({title: "')
			html.push(track.title.to_s)
			html.push('", src: "')
			html.push(Rails.application.routes.url_helpers.stream_url(track, :only_path => true))
			html.push('", duration: ')
			html.push(track.duration.to_s)
			html.push('});')
		}
		html.push('</script>')
		html.join.html_safe
	end
end

app/views/tracks/_form.html.erb
<%= form_for @track do |f| %>
	<% if @track.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>
			<ul>
			<% @track.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
	<% end %>
	<p>
		<%= f.label :location %>: <%= @track.location %>
	</p>
	<p>
		<%= f.label :track_no %><br/>
		<%= f.number_field :track_no %><br/>
	</p>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %><br/>
	</p>	
	<p>
		<%= f.label :album_id %><br/>
		<%= f.select :album_id, options_for_select(Album.options_for_select, @track.album_id)%><br/>
	</p>	
	<p>
		<%= f.label :artist_id %><br/>
		<%= f.select :artist_id, options_for_select(Artist.options_for_select, @track.artist_id)%><br/>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<h1>Tracks</h1>
<table>
  <tr>
	<th>ID</th>
    <th>Title</th>
    <th>Location</th>
	<th></th>
  </tr>
 
  <% @tracks.each do |track| %>
    <tr>
      <td><%= track.id %></td>
      <td><%= track.title %></td>
      <td><%= track.location %></td>
	  <td><%= link_to 'Show', track %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Artists', artists_path %></p>
<p><%= link_to 'Albums', albums_path %></p>

app/views/tracks/show.html.erb
<audio autoplay="autoplay" controls>
	<source src="<%=stream_url @track %>" type=audio/mpeg>
</audio>

<p>
	<strong>Track No.:</strong>
	<%= @track.track_no %>
</p>

<p>
	<strong>Title:</strong>
	<%= @track.title %>
</p>

<p>
	<strong>Location:</strong>
	<%= @track.location %>
</p>

<p>
	<strong>Album:</strong>
	<%= @track.album.nil? ? "Undefined" : link_to(@track.album.title,@track.album) %>
</p>

<p>
	<strong>Artist:</strong>
	<%= @track.artist.nil? ? "Undefined" : link_to(@track.artist.name,@track.artist) %>
</p>



<%= link_to "Edit", edit_track_path(@track) %><br/>
<%= link_to 'Artists', artists_path %><br/>
<%= link_to 'Albums', albums_path %><br/>
<%= link_to 'Tracks', tracks_path %>