config/routes.rb
MediaServer::Application.routes.draw do
  get "music/home"

  root 'music#home'

	get 'tracks/gather' => 'tracks#gather'
	get 'tracks/stream/:id' => 'tracks#stream', :as => :stream
  	resources :tracks, :only => [:show, :edit, :update, :index]

	get 'artists/data/:mode' => 'artists#data', :as => :artists_data
	resources :albums, :artists

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :albums
	has_many :tracks
	
	def self.options_for_select
		artists = self.all
		options = artists.sort{|a,b|a.name <=> b.name}.map{|artist| [artist.name, artist.id]}
		options.unshift(["None", nil])
	end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

	def index
		@artists = Artist.includes(:albums).where("albums.artist_id IS NOT NULL")
	end
	
	def data
		if (params[:mode] == "album") then
			@artists = Artist.includes(:albums).where("albums.artist_id IS NOT NULL")
		elsif (params[:mode] == "track") then
			@artists = Artist.includes(:tracks).where("tracks.artist_id IS NOT NULL")
		else
			@artists = Artist.all
		end
		#render text: params[:mode]
		#render action: "data.js.erb", layout: false, content_type: "text/javascript"
		#render json: @artists

		render :json => @artists.to_json(only: [:id, :name])
	end

	def new
		@artist = Artist.new
	end
	
	def show
		@artist = Artist.find(params[:id])
	end
	
	def edit
		@artist = Artist.find(params[:id])
	end
	
	def update
		@artist = Artist.find(params[:id])
		
		if (@artist.update(artist_params))
			redirect_to @artist
		else
			render 'edit'
		end
			
	end
	
	def create
		@artist = Artist.new(artist_params)
		if @artist.save
			redirect_to artists_path
		else
			render 'new'
		end
	end
	
	def destroy
		@artist = Artist.find(params[:id])
		@artist.albums.each{|album|
			album.artist_id = nil
			album.save
		}
		@artist.destroy
		
		redirect_to artists_path
	end
	
	private
	def artist_params
		params.require(:artist).permit(:name)
	end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
	<% if @artist.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>
			<ul>
			<% @artist.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
	<% end %>
	<p>
		<%= f.label :name %><br/>
		<%= f.text_field :name %><br/>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Artists</h1>

<%= link_to "New Artist", new_artist_path %>
<table>
	<th>Id</th>
	<th>Name</th>
	<th></th>
	<th></th>
	<th></th>
<% @artists.each do |artist| %>
	<tr>
	<td><%= artist.id %></td>
	<td><%= artist.name %></td>
	<td><%= link_to "Show", artist %></td>
	</tr>
<% end %>

</table>

<p><%= link_to "Albums", albums_path %></p>
<p><%= link_to "Tracks", tracks_path %></p>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<div id='musicplayer' class='centre'></div>

<p>
	<strong>Name:</strong>
	<%= @artist.name %>
</p>

<p>
	<strong>Albums:</strong><br/>
	<% @artist.albums.each {|album| %>
		<%= link_to album.title,album %><br/>
	<% } %>
</p>

<p>
	<strong>Tracks:</strong><br/>
	<% @artist.tracks.each {|track| %>
		<%= link_to track.title,track %><br/>
	<% } %>
</p>

<%= link_to "Edit", edit_artist_path(@artist) %><br/>
<%= link_to 'Artists', artists_path %><br/>
<%= link_to 'Albums', albums_path %>

<%= TracksHelper.musicplayer_script(@artist.tracks) %>