config/routes.rb
MediaServer::Application.routes.draw do
  get "music/home"

  root 'music#home'

	get 'tracks/gather' => 'tracks#gather'
	get 'tracks/stream/:id' => 'tracks#stream', :as => :stream
  	resources :tracks, :only => [:show, :edit, :update, :index]

	get 'artists/data/:mode' => 'artists#data', :as => :artists_data
	resources :albums, :artists

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :artist
	has_many :tracks
	
	def self.options_for_select
		albums = self.all
		options = albums.sort{|a,b|a.title <=> b.title}.map{|album| [album.title, album.id]}
		options.unshift(["None", nil])
	end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	def index
		@albums = Album.all.order(:title)
	end
	
	def new
		@album = Album.new
	end
	
	def create
		@album = Album.new(album_params)
		if @album.save
			redirect_to albums_path
		else
			render 'new'
		end
	end
	
	def show
		@album = Album.find(params[:id])
	end
	
	def edit
		@album = Album.find(params[:id])
	end
	
	def update
		@album = Album.find(params[:id])
		
		if (@album.update(album_params))
			redirect_to albums_path
		else
			render "edit"
		end
	end
	
	def destroy
		@album = Album.find(params[:id])
		
		@album.tracks.each{|track|
			track.album_id = nil
			track.save
		}
		
		@album.destroy
		
		redirect_to albums_path
	end
	
	private
	def album_params
		params.require(:album).permit(:title, :artist_id)
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for @album do |f| %>
	<% if @album.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>
			<ul>
			<% @album.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
	<% end %>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %><br/>
	</p>
	
	<p>
		<%= f.label :artist_id %>
		<%= f.select :artist_id, options_for_select(Artist.options_for_select, @album.artist_id) %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Albums</h1>

<%= link_to 'New Album', new_album_path %>
<table>
	<th>Id</th>
	<th>Title</th>
	<th></th>
	<th></th>
	<th></th>
	<!--<th>Artist</th>-->
<% @albums.each do |album| %>
	<tr>
	<td><%= album.id %></td>
	<td><%= album.title %></td>
	<td><%= link_to "Show", album %></td>
	</tr>
<% end %>

</table>

<p><%= link_to 'Artists', artists_path %></p>
<p><%= link_to 'Tracks', tracks_path %></p>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<div id='musicplayer' class='centre'></div>

<p>
	<strong>Title:</strong>
	<%= @album.title %>
</p>

<p>
	<strong>Artist:</strong>
	<%= @album.artist.nil? ? "Undefined" : link_to(@album.artist.name,@album.artist) %>
</p>

<p>
	<strong>Tracks:</strong><br/>
	<% sorted_tracks = @album.tracks.sort {|x,y| x.track_no <=> y.track_no} %>
	<% sorted_tracks.each {|track| %>
		<%= link_to track.title,track %><br/>
	<% } %>
</p>


<%= link_to "Edit", edit_album_path(@album) %><br/>
<%= link_to 'Artists', artists_path %><br/>
<%= link_to 'Albums', albums_path %>

<%= TracksHelper.musicplayer_script(sorted_tracks) %>